version: 0.1.0.{build}
configuration: Release
platform: Any CPU
build_script:
- cmd: Build.cmd
artifacts:
- path: TopOA.Core\bin\Release\TopOA.Core.0.1.0.nupkg
environment:
  matrix:
    - CLI_VERSION: Latest
branches:
  only:
    - master
deploy:  
- provider: NuGet
  server: https://www.myget.org/F/belgaard-ci/api/v2/package
  api_key:
    secure: whdEZ/zZL09ILdI18RLIeGgL71etbLNJpiIY4hNBhHMbZVZ82ziU6tSyMR4gw1mt
  skip_symbols: true
  on:
    branch: master	